module.exports = [
    {
      item_name: "Rent",
      amount: -2300,
      date: "01-01-2023",
      from: "bank",
      category: "housing",
    },
    {
      item_name: "Car Note",
      amount: -300,
      date: "17-01-2023",
      from: "bank",
      category: "auto",
    },
    {
        item_name: "Optimum",
        amount: -85,
        date: "08-01-2023",
        from: "internet",
        category: "internet",
    },
    {
        item_name: "Income",
        amount: 3500,
        date: "02-01-2023",
        from: "employer",
        category: "salary",
    },
    {
        item_name: "Stop and Shop",
        amount: -300,
        date: "16-01-2023",
        from: "supermarket",
        category: "Groceries",
    },
    {
        item_name: "Nails",
        amount: -90,
        date: "23-01-2023",
        from: "Nail Salon",
        category: "beauty",
    },
    {
        item_name: "Hair",
        amount: -30,
        date: "23-01-2023",
        from: "Hair Salon",
        category: "beauty",
    },
  ];